[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "beautifulsoup4>=4.13.4",
    "flask>=3.1.1",
    "prompt-toolkit>=3.0.51",
    "rapidfuzz>=3.13.0",
    "requests>=2.32.4",
    "rich>=14.1.0",
]
